### ISSUE TITLE
Alphonso's review

### ISSUE THREAD

**Issue by camelPhonso** [fac28/private-servants#33]
- love the idea! made me chuckle
- looks like you might be over-complicating really simple issues. Here's one:
```javascript
// in FilterAndDisplay.jsx
<Select
	className="custom-select"
	classNames={{
	control: (state) =>
		state.isFocused ?    // this is cool
		'border-red-600' :   // but why have it??
		'border-grey-300', 
	}}
	options={options}
	value={selectedOption}
	onChange={setSelectedOption}
>		
</Select>
```
```css
/* why not this in your global.css ?? */
.custom-select {
	border-color: rgb(75 85 99); /* this matches the tailwind class */
}

.custom-select:active {
	border-color: rgb(220 38 38);
}
```
- this two-part filter is awesome! ![[Screenshot 2023-10-25 at 17.29.44.png]]
- why does your `RenderServants` component not simply display the filter conditionally, instead of living in a different route?
   - the power of React is in building "single page apps"!
```javascript
const [max, setMax] = useState(Math.ceil(Math.max(...allServants)))
	// I literally copied the formula from an old project
	// I don't remember how it works

	// but now your max is the highest price you have available

	// you can just display everything with the filter in one page
```
